### PR TITLE
Upgrade to Fluent assertions v6

### PR DESCRIPTION
**Pull request by rikrak**
Related to #42 

I've had to update the version of the .NET Framework in use to v4.7
I've also migrated most of the projects to package referencing to make it easier to switch target frameworks
All tests pass locally

### CODE REVIEW

**Comment by rikrak** [comment]
@kevinkuszyk Really sorry to pester. Any chance you could look at this?  It's holding up my current project :-(  
Thanks!

**Comment by rikrak** [comment]
@dennisdoomen Really sorry to pester - are you able to process this pull request?

**Comment by dennisdoomen** [comment]
I'm not the maintainer of this repo.

**Comment by rikrak** [comment]
Many thanks @kevinkuszyk 
Again, sorry for the pester :-)

**Comment by rikrak** [comment]
Will the nuget package be produced automatically?

**Pull request merged**
